package twotech.plugin.magicHeroes.stat

enum class StatType {
    ATTACK_DAMAGE,
    MAX_HEALTH,
    HEALTH_REGEN,
    MAX_MANA,
    MANA_REGEN,
    DEFENSE,
    ARMOR,
    MOVEMENT_SPEED,
    CRITICAL_STRIKE_CHANCE,
    CRITICAL_STRIKE_POWER,
    ARMOR_PENETRATION,
    MAGIC_PENETRATION,
    FIRE_DAMAGE,
    ICE_DAMAGE,
    LIGHTNING_DAMAGE,
    POISON_DAMAGE,
    FIRE_RESISTANCE,
    ICE_RESISTANCE,
    LIGHTNING_RESISTANCE,
    POISON_RESISTANCE,
    LIFESTEAL,
    THORNS,
    LUCK,
    EXPERIENCE_BONUS
}
